In [1]:
import pandas as pd
import yaml

In [4]:
df = pd.read_csv(r"C:\Users\karthik.kishor\Desktop\Projects\mti_brain\brain\semantic_model_generator\output\mti-brain - testing prompt results(tables).csv")

df2 = pd.read_excel(r"C:\Users\karthik.kishor\Desktop\Projects\mti_brain\brain\semantic_model_generator\output\inferred_relationships 1.xlsx")

In [5]:
df = df[["from_table", "from_column", "to_table", "to_column"]]
df.head()

          from_table             from_column      to_table to_column
0         ach_return             company_ref       company      code
1         ach_return   original_transfer_ref      transfer      uuid
2           acquirer                bank_ref          bank      code
3           acquirer  settlement_account_ref  bank_account      code
4  acquirer_contract            acquirer_ref      acquirer      code

In [6]:

df2 = df2[df2['from_schema'] == 'lpp']
df2 = df2[["from_table", "from_column", "to_table", "to_column"]]
df2.head()

            from_table       from_column      to_table    to_column
0           ach_return  bank_account_ref  bank_account         code
1           ach_return       company_ref  bank_account  company_ref
2    acquirer_contract      acquirer_ref      acquirer         code
3  acquirer_sla_metric      acquirer_ref      acquirer         code
4             acquirer          bank_ref          bank         code

In [7]:
df.count()

from_table     180
from_column    180
to_table       180
to_column      180
dtype: int64

In [8]:
df2.count()

from_table     121
from_column    121
to_table       121
to_column      121
dtype: int64

In [9]:
merged = pd.merge(df, df2, on=['from_table', 'from_column', 'to_table', 'to_column'], how='outer', indicator=True)
merged

,from_table,from_column,to_table,to_column,_merge
0,ach_return,bank_account_ref,bank_account,code,both
1,ach_return,company_ref,bank_account,company_ref,right_only
2,ach_return,company_ref,company,code,left_only
3,ach_return,original_transfer_ref,transfer,uuid,left_only
4,acquirer,bank_ref,bank,code,both
...,...,...,...,...,...
197,v_sme_transcript_chunk_indexable,chunk_uuid,tribal_knowledge_fact,uuid,right_only
198,v_tribal_fact_indexable,fact_uuid,tribal_knowledge_fact,uuid,right_only
199,wcf_document,buyer_company,company,code,left_only
200,wcf_document,supplier_ref,third_party,code,left_only
201,working_capital_metric,company_ref,company,code,left_only

In [10]:
merged = merged.drop(columns=['_merge']).drop_duplicates()
merged

,from_table,from_column,to_table,to_column
0,ach_return,bank_account_ref,bank_account,code
1,ach_return,company_ref,bank_account,company_ref
2,ach_return,company_ref,company,code
3,ach_return,original_transfer_ref,transfer,uuid
4,acquirer,bank_ref,bank,code
...,...,...,...,...
197,v_sme_transcript_chunk_indexable,chunk_uuid,tribal_knowledge_fact,uuid
198,v_tribal_fact_indexable,fact_uuid,tribal_knowledge_fact,uuid
199,wcf_document,buyer_company,company,code
200,wcf_document,supplier_ref,third_party,code
201,working_capital_metric,company_ref,company,code

In [11]:
output = {"relationships": merged.to_dict(orient="records")}

with open("relationships.yml", "w") as f:
    yaml.dump(output, f, default_flow_style=False, sort_keys=False)

print("Written to relationships.yml")

Written to relationships.yml

In [12]:
all_tables = sorted(set(merged['from_table'].dropna()).union(set(merged['to_table'].dropna())))
all_tables

['ach_return',
 'acquirer',
 'acquirer_contract',
 'acquirer_sla_metric',
 'ap_invoice',
 'app_user',
 'ar_invoice',
 'audit_trail',
 'bank',
 'bank_account',
 'bank_account_group',
 'bank_account_group_member',
 'bank_account_signatory',
 'bank_branch',
 'bank_fee',
 'bank_group',
 'bank_group_member',
 'bank_service_type',
 'bank_statement_balance',
 'benchmark_rate',
 'borrowing',
 'brain_evaluation',
 'budget_code',
 'capital_allocation_actual',
 'card_authorization',
 'card_bin_range',
 'card_network',
 'card_rebate_earning',
 'card_rebate_program',
 'card_settlement_batch',
 'card_settlement_line',
 'cash_balance',
 'cash_flow',
 'cash_flow_code',
 'chargeback',
 'company',
 'company_financial_metric',
 'company_group',
 'company_group_member',
 'counterparty_exposure',
 'credit_facility',
 'credit_rating',
 'cross_border_payment_leg',
 'currency',
 'data_permission',
 'data_permission_profile',
 'derivative_mtm',
 'equity_action',
 'fee_rate_card',
 'forecast_cash_flow',
 'forecast_snapshot',
 'forecast_vs_actual',
 'fraud_detection_event',
 'fraud_loss',
 'fx_exposure_forecast',
 'fx_forward',
 'fx_rate',
 'gen_company_region',
 'gl_account',
 'gl_balance',
 'gl_reconciliation',
 'hedge_dedesignation',
 'hedge_relationship',
 'intercompany_transaction',
 'interest_accrual',
 'investment_instrument',
 'investment_position',
 'investment_transaction',
 'kg_relationship',
 'letter_of_credit',
 'liquidity_policy',
 'macro_indicator',
 'mapping_entry',
 'mapping_table',
 'membership_fee',
 'payment_exception',
 'payment_file',
 'payment_hub_throughput',
 'payment_transaction',
 'peer_company',
 'peer_company_metric',
 'pension_plan',
 'pension_valuation',
 'pos_transaction',
 'sme_feedback_session',
 'sme_transcript_chunk',
 'stress_run_result',
 'stress_scenario',
 'sweep_execution',
 'sweep_instruction',
 'third_party',
 'third_party_bank_account',
 'third_party_category',
 'third_party_category_assignment',
 'transfer',
 'tribal_knowledge_entity_link',
 'tribal_knowledge_fact',
 'user_group',
 'user_group_member',
 'user_profile_assignment',
 'v_sme_transcript_chunk_indexable',
 'v_tribal_fact_indexable',
 'wcf_document',
 'webhook_event',
 'working_capital_metric']